### ISSUE TITLE
Darkmode is not loading if behind pfsense router 

### ISSUE THREAD

**Issue by corgan2222** [shouhaiel1/AI-powered-surveillance-using-raspberry-pi#1]
the app loads, but with a white layout.

DevTools Error:
GET https://cdn.jsdelivr.net/npm/darkmode-js@1.5.5/lib/darkmode-js.min.js net::ERR_CERT_AUTHORITY_INVALID
(index):251 Uncaught ReferenceError: Darkmode is not defined
    at (index):251
(anonymous) @ (index):251

This happend, if the network traffic is watched by any firewall with spamhaus dln. The URL cdn.jsdelivr.net is marked as not save.
In my case, i could allow the traffic, but maybe its a good idea to include the js file to your repo.

**Comment by souhaiel1** [comment]
I will include it , thanks for the feedback !
