### ISSUE TITLE
IP Cameras

### ISSUE THREAD

**Issue by corgan2222** [shouhaiel1/AI-powered-surveillance-using-raspberry-pi#3]
Do you have plans to support IP Cameras?
I would think that the most Cameras are installed seperatly without a connected Raspi.

the code is easy, just call
video_capture = cv2.VideoCapture('rtsp://user:password@192.168.x.x/url') #sample
insted of 
video_capture = cv2.VideoCapture(0)

**Comment by souhaiel1** [comment]
I will add this remark in the description !
